const CategoriesList = [
  'Arts & Entertainment',
  'Autos & Vehicles',
  'Beautify & Fitness',
  'Books & Literature',
  'Business & Industrial',
  'Computers & Electronics',
  'Finance',
  'Food & Drink',
  'Gaming',
  'Health',
  'Hobbies & Leisure',
  'Home & Garden',
  'Internet',
  'Education',
  'Government',
  'News',
  'Community',
  'People & Society',
  'Pets & Animals',
  'Real Estate',
  'Science',
  'Shopping',
  'Sports',
  'Travel',
  'NSFW',
  'Other',
];

module.exports = CategoriesList;